##Example mqtt configuration for CyberPower UPS Linux Software

mqtt:
  - sensor:
    - name: "UPS State"
      state_topic: "homeassistant/sensor/ups/state"
      unique_id: "ups_state"

    - name: "UPS Power Supply"
      state_topic: "homeassistant/sensor/ups/power_supply"
      unique_id: "ups_power_supply"

    - name: "UPS Utility Voltage"
      state_topic: "homeassistant/sensor/ups/utility_voltage"
      unit_of_measurement: "V"
      unique_id: "ups_utility_voltage"

    - name: "UPS Output Voltage"
      state_topic: "homeassistant/sensor/ups/output_voltage"
      unit_of_measurement: "V"
      unique_id: "ups_output_voltage"

    - name: "UPS Battery Capacity"
      state_topic: "homeassistant/sensor/ups/battery_capacity"
      unit_of_measurement: "%"
      unique_id: "ups_battery_capacity"

    - name: "UPS Remaining Runtime"
      state_topic: "homeassistant/sensor/ups/remaining_runtime"
      unit_of_measurement: "min"
      unique_id: "ups_remaining_runtime"

    - name: "UPS Load Power"
      state_topic: "homeassistant/sensor/ups/load_watt"
      unit_of_measurement: "W"
      unique_id: "ups_load_watt"

    - name: "UPS Line Interaction"
      state_topic: "homeassistant/sensor/ups/line_interaction"
      unique_id: "ups_line_interaction"

    - name: "UPS Last Power Event"
      state_topic: "homeassistant/sensor/ups/last_power_event"
      unique_id: "ups_last_power_event"
